app:
  address: 0xc200
  end_address: 0x46000
  region: flash_primary
  size: 0x39e00
mcuboot:
  address: 0x0
  end_address: 0xc000
  placement:
    before:
    - mcuboot_primary
  region: flash_primary
  size: 0xc000
mcuboot_pad:
  address: 0xc000
  end_address: 0xc200
  placement:
    align:
      start: 0x1000
    before:
    - mcuboot_primary_app
  region: flash_primary
  size: 0x200
mcuboot_primary:
  address: 0xc000
  end_address: 0x7ff00
  orig_span: &id001
  - app
  - mcuboot_pad
  region: flash_primary
  sharers: 0x1
  size: 0x73f00
  span: *id001
mcuboot_primary_app:
  address: 0xc200
  end_address: 0x7ff00
  orig_span: &id002
  - app
  region: flash_primary
  size: 0x73d00
  span: *id002
mcuboot_secondary:
  address: 0x7ff00
  end_address: 0x80000
  placement:
    after:
    - mcuboot_primary
  region: flash_primary
  share_size:
  - mcuboot_primary
  size: 0x100
sram_primary:
  address: 0x20000000
  end_address: 0x20020000
  region: sram_primary
  size: 0x20000
